"""Regenerate the exact binary Prefetch (.pf) demo inputs for demo 01.

Standard library only. The byte payloads below are the literal contents of two
valid uncompressed version-23 (Windows 7) prefetch files, so the demo input is
fully reproducible without shipping binaries.

Run:  python demos/01-basic/make_demo.py
"""
import base64
from pathlib import Path

# Real v23 prefetch bytes (base64). POWERSHELL run once, loading a PS1 from a
# Temp staging dir; NOTEPAD run 42 times from System32.
_FILES = {
    "POWERSHELL.EXE-AF1C2D3E.pf": (
        "FwAAAFNDQ0ERAAAASgIAAFAATwBXAEUAUgBTAEgARQBMAEwALgBFAFgARQAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4tHK8AAAAAAAAAAAAAAAAAAAAAAAAAAPA"
        "AAABaAQAAAAAAAAEAAAAAAAAAAAAAAAAAAACApxBtivbcAQAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAXABWAE8ATABVAE0ARQB7ADAAMQBkADgA"
        "fQBcAFcASQBOAEQATwBXAFMAXABTAFkAUwBUAEUATQAzADIAXABXAEkATgBEAE8AVwBT"
        "AFAATwBXAEUAUgBTAEgARQBMAEwAXABWADEALgAwAFwAUABPAFcARQBSAFMASABFAEwA"
        "TAAuAEUAWABFAAAAXABWAE8ATABVAE0ARQB7ADAAMQBkADgAfQBcAFUAUwBFAFIAUwBc"
        "AEMASABSAEkAUwBcAEEAUABQAEQAQQBUAEEAXABMAE8AQwBBAEwAXABUAEUATQBQAFwA"
        "UwBUAEEARwBFAFwAUABBAFkATABPAEEARAAuAFAAUwAxAAAAXABWAE8ATABVAE0ARQB7"
        "ADAAMQBkADgAfQBcAFcASQBOAEQATwBXAFMAXABTAFkAUwBUAEUATQAzADIAXABOAFQA"
        "RABMAEwALgBEAEwATAAAAA=="
    ),
    "NOTEPAD.EXE-1B2C3D4E.pf": (
        "FwAAAFNDQ0ERAAAAngEAAE4ATwBUAEUAUABBAEQALgBFAFgARQAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAE49LBsAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAACu"
        "AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABqqNk/XcAQAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAAAAXABWAE8ATABVAE0ARQB7ADAAMQBkADgA"
        "fQBcAFcASQBOAEQATwBXAFMAXABTAFkAUwBUAEUATQAzADIAXABOAE8AVABFAFAAQQBE"
        "AC4ARQBYAEUAAABcAFYATwBMAFUATQBFAHsAMAAxAGQAOAB9AFwAVwBJAE4ARABPAFcA"
        "UwBcAFMAWQBTAFQARQBNADMAMgBcAEsARQBSAE4ARQBMADMAMgAuAEQATABMAAAA"
    ),
}


def main() -> None:
    here = Path(__file__).resolve().parent
    for name, b64 in _FILES.items():
        (here / name).write_bytes(base64.b64decode(b64))
        print(f"wrote {name}")


if __name__ == "__main__":
    main()
